export const GET_TT_RAP = 'GET_TT_RAP'
export const GET_TT_CUMRAP = 'GET_TT_CUMRAP'
export const GET_TT_LICHCHIEU_RAP = 'GET_TT_LICHCHIEU_RAP'
export const GET_TT_LICHCHIEU_PHIM = 'GET_TT_LICHCHIEU_PHIM'